apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    deployment.kubernetes.io/revision: "1.0.1"
spec:
  ingressClassName: nginx
  rules:
    - host: api.bidding.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-api-internal
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ui
  annotations:
    deployment.kubernetes.io/revision: "1.0.1"
spec:
  ingressClassName: nginx
  rules:
    - host: bidding.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-ui-internal
                port:
                  number: 3000
